dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
env:
  global:
    secure: ofEIs51j7V3XDbS+5m9qz6fFtBcN+GT2ZkSYkssYakAdEHLJXMlpre0hpgpYI8Sod/Yy2bwRsd8L6tYnvD3lEHnkN7QoWrxFV2+DWyFnLPV/ES/ET+VARlzSHy6BHCavwDVe/JZvDbIRU9rbMP7L1OiaDax6tb/HX9rj1ZxpB5oNaxBch9S1pym6JhvEcmBs7DSE1KVhoqsogWPodGnNV04M36eYOj7byPSAtYKOmHgS5ki5miS4ecCBczwENGQYF+QqtBByznFOhn8KO+GLximBl5rpwhJgZ0UJiPxn+y6e4Pei9RKBz6RyUCORE/HYQzWnfsKwavX8WptsUM3uCylSIsRcyl21V8DUBznp181uKf671+G/gLE+ngH4YY7lA9PdgZya0+dCpDd1r/8Ri6ki+SlRzA9MxqKpD8eOqGhhc/yRUfmUXiQQ2ivF/Ia3fp8saJr6qFRdSgyL0eU1s5QCyW/8CHjiDRE3qppibEQ9/WQlP+ANma1vAK+V/nopWe8dIGaHMqDyGLoQTC2lBO5RpIBTUs3CZaPzLu7udIm3h4bMLh1Otf/eXRB3ZZTEcVavM8V+TAi2LcjWDdzcxTMO88JrVgs4gQwYjiMDoiwEej1AD4fDbDE4aqz/TPPWmWY6fpkt6MdeY3A9ft8LzAmW3i0uZjy2vjY6tkM6fU4=
notifications:
  slack:
    rooms:
      secure: dXnVuqpEqabb2iBZL+/d7XsvYw0JNiODlf6XzSDA3ysvhZMysF+A8f4F4eeN0/ZqmfZUJ7Cw8UM6r/CIydsTsJhsnz0iDgYJ8lFIpShclZdQ+xdSQPDFUeiV2+UthfCY6ijn6AIuIklEjDEilMHnQ363/ZNZvJUZ/H1N0XNXXXG3w66tLMBmreA7gtwMp3HNk8K25YJJOjXWG6f6h4Q+t47xI6cOiEZ3KHTcXGp1jnMl5GMN0nHPFgUXp0pnQNouFdsorf4aoU9ORwqDPsIwXaVPLJnCvXK4Jfd5zUSAdBIv2bF9D/iNiSNMqxgdEPTDFvmYroJNagszE/+1GFDyboMjcq9lo9L2CUPcaTRWXU6tVaOWENyDNfmkManmI04mjRSl5KPcLEKBEhUU6oMAp/f7x//yFWj0j2EFJqX54RbUdxCFPXroBfxX8hAOsiQuKoCxZr1ol/F8djCtkafl/GJw/Whi10t/XqdEu3hvkwOp7fiY3bAlOjLWFPHQL7LtKLrGY0yPNf50BhWVdRn9vOdl+gxA4+yHB7+1VCMH7AP066okN2eMW3+0hGXK5eWt46Bw28Qegvc2DnfBVi+TBlpTnw03ELbSC2K62oxz2FpYLibQbo4OydZI9y2gCRGb1p/rtfVuF4jgxoa41Eony3yYhQgy2+6I8MBRcUGclNU=
