---
- name: Deploy OTUS Reddit
  hosts: tag_docker-host
  become: true
  tasks:
  - name: Deploy reuuke/otus-reddit
    docker_container:
      name: reddit
      image: reuuke/otus-reddit:1.0
      ports:
        - "9292:9292"
