kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: c9Sq9jDcCdNIZy29Q7ZUmIctJUF7sbm2o9sFm+Kk/sU=
      - identity: {}
